### PR TITLE
Add @hoechenberger to list of maintainers

### PR DESCRIPTION
**Pull request by hoechenberger**

### CODE REVIEW

**Comment by hoechenberger** [comment]
Friendly ping @marcelotrevisani :)

**Comment by marcelotrevisani** [comment]
@conda-forge-admin , please rerender

**Comment by marcelotrevisani** [comment]
> Friendly ping @marcelotrevisani :)

Sorry about the delay, we receive a lot of notifications, some might got lost :/
Thanks for the pinging! :)

**Review by marcelotrevisani — APPROVED** [review]

**Review by marcelotrevisani — APPROVED** [review]

**Comment by hoechenberger** [comment]
Thank you!

**Pull request merged**
